
import javax.swing.JOptionPane;

public class VentanaCursos extends javax.swing.JFrame {

    private final javax.swing.JFrame ventanaAnterior;
    private final GestionCursos gestionCursos;

    /**
     * Creates new form VentanaCursos
     */
    public VentanaCursos() {
        this(null, null);
    }

    public VentanaCursos(javax.swing.JFrame ventanaAnterior, GestionCursos gestionCursos) {
        this.ventanaAnterior = ventanaAnterior;
        this.gestionCursos = gestionCursos;

        initComponents();
        getContentPane().setBackground(new java.awt.Color(15, 23, 42));
        setLocationRelativeTo(ventanaAnterior);

        jButton3.addActionListener(e -> {
            dispose();
            if (this.ventanaAnterior != null) {
                this.ventanaAnterior.setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Cursos");
        setBackground(new java.awt.Color(30, 41, 59));

        jButton1.setText("Agregar curso");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mostrar cursos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Volver a administración");

        jButton4.setText("Editar curso");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Buscar curso");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton5)
                            .addComponent(jButton4))))
                .addGap(154, 154, 154))
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String nombre = JOptionPane.showInputDialog(this, "Ingrese el nombre del curso:");

        if (nombre == null) {
            return;
        }

        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del curso:");

        if (codigo == null) {
            return;
        }

        String profesorJefe = JOptionPane.showInputDialog(this, "Ingrese el nombre del profesor jefe:");

        if (profesorJefe == null) {
            return;
        }

        nombre = nombre.trim();
        codigo = codigo.trim();
        profesorJefe = profesorJefe.trim();

        if (nombre.isEmpty() || codigo.isEmpty() || profesorJefe.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los datos.");
            return;
        }

        boolean cursoAgregado = gestionCursos.agregarCurso(nombre, codigo, profesorJefe);

        if (cursoAgregado) {
            JOptionPane.showMessageDialog(this, "Curso agregado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "Ya existe un curso con ese código.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (gestionCursos.getCursos().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay cursos registrados.");
            return;
        }

        String listaCursos = "";

        for (Curso curso : gestionCursos.getCursos().values()) {
            listaCursos = listaCursos + "Código: " + curso.getCodigo() + "\nNombre: " + curso.getNombre() + "\nProfesor jefe: " + curso.getProfesorJefe() + "\n\n";
        }

        JOptionPane.showMessageDialog(this, listaCursos, "Cursos registrados", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del curso que desea editar:");
        if (codigo == null) {
            return;
        }

        String nuevoNombre = JOptionPane.showInputDialog(this, "Ingrese el nuevo nombre del curso:");
        if (nuevoNombre == null) {
            return;
        }

        String nuevoProfesorJefe = JOptionPane.showInputDialog(this, "Ingrese el nuevo profesor jefe:");
        if (nuevoProfesorJefe == null) {
            return;
        }

        codigo = codigo.trim();
        nuevoNombre = nuevoNombre.trim();
        nuevoProfesorJefe = nuevoProfesorJefe.trim();

        if (codigo.isEmpty() || nuevoNombre.isEmpty() || nuevoProfesorJefe.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los datos.");
            return;
        }

        boolean cursoEditado = gestionCursos.editarCurso(codigo, nuevoNombre, nuevoProfesorJefe);

        if (cursoEditado) {
            JOptionPane.showMessageDialog(this, "Curso editado correctamente.");
        } else {
            JOptionPane.showMessageDialog(this, "No existe un curso con ese código.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String codigo = JOptionPane.showInputDialog(this, "Ingrese el código del curso:");
        if (codigo == null) {
            return;
        }

        codigo = codigo.trim();

        if (codigo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el código del curso.");
            return;
        }

        Curso curso = gestionCursos.buscarCurso(codigo);

        if (curso == null) {
            JOptionPane.showMessageDialog(this, "No existe un curso con ese código.");
            return;
        }

        String resultado = "Código: " + curso.getCodigo() + "\nNombre: " + curso.getNombre() + "\nProfesor jefe: " + curso.getProfesorJefe();
        JOptionPane.showMessageDialog(this, resultado, "Curso encontrado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
